
import Oyuncu.Oyuncular.BilgisayarOyuncusu;
import Sınıflar.Pokemon;
import Sınıflar.pokemonlar.pikachu;
import Sınıflar.pokemonlar.bulbasaur;
import Sınıflar.pokemonlar.charmander;
import Sınıflar.pokemonlar.squirtel;
import Sınıflar.pokemonlar.zubat;
import Sınıflar.pokemonlar.psyduck;
import Sınıflar.pokemonlar.snorlax;
import Sınıflar.pokemonlar.butterfree;
import Sınıflar.pokemonlar.jigglypuff;
import Sınıflar.pokemonlar.meowth;
import java.util.ArrayList;
import Oyuncu.Oyuncular.InsanOyuncusu;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author husey
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    InsanOyuncusu insan;
    BilgisayarOyuncusu pc1, pc2;
    
    public pikachu pikachu = new pikachu(40, 1, "Pikachu", "Elektrik");
    public bulbasaur bulbasaur = new bulbasaur(50, 2, "Bulbasaur", "Çim");
    public charmander charmander = new charmander(60, 3, "Charmander", "Ateş");
    public squirtel squirtel = new squirtel(30, 4, "Squirtel", "Su");
    public zubat zubat = new zubat(50, 5, "Zubat", "Hava");
    public psyduck psyduck = new psyduck(20, 6, "Psyduck", "Su");
    public snorlax snorlax = new snorlax(30, 7, "Snorlax", "Normal");
    public butterfree butterfree = new butterfree(10, 8, "Butterfree", "Hava");
    public jigglypuff jigglypuff = new jigglypuff(70, 9, "Jigglyppuff", "Su");
    public meowth meowth = new meowth(40, 10, "Meowth", "Normal");
    public Pokemon insanSecilen, pcSecilen; 
    int secim1, secim2, idSecim1, idSecim2, sayac1=0, sayac2=0, sayac3 = 2, anaSecim;
    String tiklanan, tiklanan2; 
    
    
    ArrayList<Pokemon> kartDestesi;
    ArrayList<Integer> kontrolListesi;
    ArrayList<Integer> blokList;
    ArrayList<Integer> blokList2;
    
    //https://stackoverflow.com/questions/6443176/how-can-i-generate-a-random-number-within-a-range-but-exclude-some/6443346
    public static int getRandomWithExclusion(Random rnd, int start, int end, ArrayList<Integer> exclude) {
        int random = start + rnd.nextInt(end - start + 1 - exclude.size());
        for (int ex : exclude) {
            if (random < ex) {
                break;
            }
            random++;
        }
        return random;
    }
    
    public MainPage() {
        kartDestesi = new ArrayList<Pokemon>(10);
        kartDestesi.add(pikachu);
        kartDestesi.add(bulbasaur);
        kartDestesi.add(charmander);
        kartDestesi.add(squirtel);
        kartDestesi.add(zubat);
        kartDestesi.add(psyduck);
        kartDestesi.add(snorlax);
        kartDestesi.add(butterfree);
        kartDestesi.add(jigglypuff);
        kartDestesi.add(meowth);
        
        
        kontrolListesi = new ArrayList<Integer>(10);
        kontrolListesi.add(pikachu.getHasarPuani());
        kontrolListesi.add(bulbasaur.getHasarPuani());
        kontrolListesi.add(charmander.getHasarPuani());
        kontrolListesi.add(squirtel.getHasarPuani());
        kontrolListesi.add(zubat.getHasarPuani());
        kontrolListesi.add(psyduck.getHasarPuani());
        kontrolListesi.add(snorlax.getHasarPuani());
        kontrolListesi.add(butterfree.getHasarPuani());
        kontrolListesi.add(jigglypuff.getHasarPuani());
        kontrolListesi.add(meowth.getHasarPuani());
        
        
        blokList = new ArrayList<Integer>();
        blokList2 = new ArrayList<Integer>();
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SavasSayfasi = new javax.swing.JPanel();
        SavasSayfasi.setVisible(false);
        Alt2 = new javax.swing.JButton();
        Alt3 = new javax.swing.JButton();
        Ust3 = new javax.swing.JButton();
        Alt1 = new javax.swing.JButton();
        Ust1 = new javax.swing.JButton();
        dagit = new javax.swing.JButton();
        Ust2 = new javax.swing.JButton();
        Ust = new javax.swing.JButton();
        Alt = new javax.swing.JButton();
        SavasButon = new javax.swing.JButton();
        WinorLose = new javax.swing.JLabel();
        insanSkor = new javax.swing.JLabel();
        pcSkor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Anasayfa = new javax.swing.JPanel();
        insanvspc_Button = new javax.swing.JButton();
        pcvspc_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        Alt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alt2ActionPerformed(evt);
            }
        });

        Alt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alt3ActionPerformed(evt);
            }
        });

        Alt1.setMaximumSize(new java.awt.Dimension(100, 50));
        Alt1.setMinimumSize(new java.awt.Dimension(100, 50));
        Alt1.setPreferredSize(new java.awt.Dimension(100, 50));
        Alt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alt1ActionPerformed(evt);
            }
        });

        Ust1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ust1ActionPerformed(evt);
            }
        });

        dagit.setText("4");
        dagit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dagitActionPerformed(evt);
            }
        });

        Ust.setText("jButton1");

        Alt.setText("jButton2");

        SavasButon.setText("Savaş");
        SavasButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavasButonActionPerformed(evt);
            }
        });

        insanSkor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        pcSkor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("İkinci Oyuncu Skor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Birinci Oyuncu Skor:");

        javax.swing.GroupLayout SavasSayfasiLayout = new javax.swing.GroupLayout(SavasSayfasi);
        SavasSayfasi.setLayout(SavasSayfasiLayout);
        SavasSayfasiLayout.setHorizontalGroup(
            SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavasSayfasiLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(insanSkor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dagit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(pcSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addComponent(Ust, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SavasSayfasiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WinorLose, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SavasSayfasiLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(SavasButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ust1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alt2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ust2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alt3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ust3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(434, 434, 434))
        );
        SavasSayfasiLayout.setVerticalGroup(
            SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SavasSayfasiLayout.createSequentialGroup()
                .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ust1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ust3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ust2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pcSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SavasSayfasiLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(dagit, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SavasSayfasiLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Alt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(SavasButon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(WinorLose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Ust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Alt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SavasSayfasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Alt2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alt1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SavasSayfasiLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insanSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        insanvspc_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        insanvspc_Button.setText("İnsan vs Bilgisayar");
        insanvspc_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insanvspc_ButtonActionPerformed(evt);
            }
        });

        pcvspc_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pcvspc_Button.setText("Bilgisayar vs Bilgisayar");
        pcvspc_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcvspc_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnasayfaLayout = new javax.swing.GroupLayout(Anasayfa);
        Anasayfa.setLayout(AnasayfaLayout);
        AnasayfaLayout.setHorizontalGroup(
            AnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnasayfaLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(insanvspc_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addComponent(pcvspc_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        AnasayfaLayout.setVerticalGroup(
            AnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnasayfaLayout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addGroup(AnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insanvspc_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcvspc_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(296, 296, 296))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Anasayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SavasSayfasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Anasayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SavasSayfasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insanvspc_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insanvspc_ButtonActionPerformed
        SavasSayfasi.setVisible(true);
        Anasayfa.setVisible(false);
        insan = new InsanOyuncusu();
        pc1 = new BilgisayarOyuncusu();
        
        
        for(int i=0;i<3;i++){
            kartDestesi = insan.KartSecim(kartDestesi,insan, i);
            
        }
        
        for(int i=0;i<3;i++){
            kartDestesi = pc1.KartSecim(kartDestesi,pc1, i);
        }
        
        
        Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(0).getPokemonID() +".jpg"));
        Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(1).getPokemonID() +".jpg"));
        Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(2).getPokemonID() +".jpg"));
        Alt1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(0).getPokemonID() +".jpg"));
        Alt2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(1).getPokemonID() +".jpg"));
        Alt3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(2).getPokemonID() +".jpg"));
        
        
        
        
       
        
    }//GEN-LAST:event_insanvspc_ButtonActionPerformed

    private void dagitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dagitActionPerformed
        if(kartDestesi.size() > 0){
            kartDestesi = insan.KartSecim(kartDestesi, insan, secim1-1);
            kartDestesi = pc1.KartSecim(kartDestesi, pc1, secim2-1);
        }
        if(insan.kartListesi.size() > 2){
            if("Alt1".equals(tiklanan)){
                Alt1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(0).getPokemonID() +".jpg")); 
            }
            if("Alt2".equals(tiklanan)){
                Alt2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(1).getPokemonID() +".jpg"));
            }
            if("Alt3".equals(tiklanan)){
                Alt3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(2).getPokemonID() +".jpg"));
            }
            if("Ust1".equals(tiklanan2)){
                Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(0).getPokemonID() +".jpg"));
            }
            if("Ust2".equals(tiklanan2)){
                Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(1).getPokemonID() +".jpg"));
            }
            if("Ust3".equals(tiklanan2)){
                Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(2).getPokemonID() +".jpg"));
            }
        }
        else
        {
            if("Alt1".equals(tiklanan)){
                Alt1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png")); 
            }
            if("Alt2".equals(tiklanan)){
                Alt2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            }
            if("Alt3".equals(tiklanan)){
                Alt3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            }
            if("Ust1".equals(tiklanan2)){
                Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            }
            if("Ust2".equals(tiklanan2)){
                Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            }
            if("Ust3".equals(tiklanan2)){
                Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            }
        }
        sayac3 -= 1;
        if(sayac3<=0)
            dagit.setEnabled(false);
        System.out.println(sayac3);
       
    }//GEN-LAST:event_dagitActionPerformed

    private void Alt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alt1ActionPerformed
        
        Random rand = new Random();
        int n = getRandomWithExclusion(rand, 0, 2, blokList);
        
        
        
        if(sayac3<=0){
            Alt1.setEnabled(false);
            
            
            
            insanSecilen = insan.kartListesi.get(0);
            Alt.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(0).getPokemonID() +".jpg"));
            idSecim1 = insan.kartListesi.get(0).getPokemonID();
            secim1 = 1;


            pcSecilen = pc1.kartListesi.get(n);
            Ust.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(n).getPokemonID() +".jpg"));
            idSecim2 = pc1.kartListesi.get(n).getPokemonID();
            secim2 = n+1;

            tiklanan = "Alt1";
            tiklanan2 = "Ust"+secim2;
            
            
            blokList.add(n);
            blokList2.add(0);
            Alt1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            
            if("Ust1".equals(tiklanan2)){
                Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust1.setEnabled(false);
            }
            if("Ust2".equals(tiklanan2)){
                Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust2.setEnabled(false);
            }
            if("Ust3".equals(tiklanan2)){
                Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust3.setEnabled(false);
            }
        }
        else{
        insanSecilen = insan.kartListesi.get(0);
        Alt.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(0).getPokemonID() +".jpg"));
        idSecim1 = insan.kartListesi.get(0).getPokemonID();
        insan.kartListesi.remove(0);
        secim1 = 1;
        
        
        pcSecilen = pc1.kartListesi.get(n);
        Ust.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(n).getPokemonID() +".jpg"));
        idSecim2 = pc1.kartListesi.get(n).getPokemonID();
        pc1.kartListesi.remove(n);
        secim2 = n+1;
        
        tiklanan = "Alt1";
        tiklanan2 = "Ust"+secim2;
        System.out.println(tiklanan2);
        }
        
    }//GEN-LAST:event_Alt1ActionPerformed

    private void pcvspc_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcvspc_ButtonActionPerformed
        // TODO add your handling code here:
        anaSecim=1;
        
        SavasSayfasi.setVisible(true);
        Anasayfa.setVisible(false);
        insan = new InsanOyuncusu();
        pc1 = new BilgisayarOyuncusu();
        
        
        for(int i=0;i<3;i++){
            kartDestesi = insan.KartSecim(kartDestesi,insan, i);
            
        }
        
        for(int i=0;i<3;i++){
            kartDestesi = pc1.KartSecim(kartDestesi,pc1, i);
        }
        
        
        Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(0).getPokemonID() +".jpg"));
        Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(1).getPokemonID() +".jpg"));
        Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(2).getPokemonID() +".jpg"));
        Alt1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(0).getPokemonID() +".jpg"));
        Alt2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(1).getPokemonID() +".jpg"));
        Alt3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(2).getPokemonID() +".jpg"));
        
        Random rand = new Random();
        int n = rand.nextInt(pc1.kartListesi.size());
        
        switch (n) {
        case 0 :
            Alt1.doClick();
            break;

        case 1 :
            Alt2.doClick();
            break;

        case 2 :
            Alt3.doClick();
            break;
        }
        
        
    }//GEN-LAST:event_pcvspc_ButtonActionPerformed

    private void Ust1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ust1ActionPerformed
        // TODO add your handling code here:
        //Ust1.setIcon(new ImageIcon("C:\\Users\\husey\\Documents\\NetBeansProjects\\Pikachu\\src\\main\\java\\Pokemon\\1.jpg"));
    }//GEN-LAST:event_Ust1ActionPerformed

    private void Alt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alt2ActionPerformed
        
        if(sayac3<=0){
            Alt2.setEnabled(false);
            Random rand = new Random();
            int n = getRandomWithExclusion(rand, 0, 2, blokList);
            blokList.add(n);
            blokList2.add(1);
            
            insanSecilen = insan.kartListesi.get(1);
            Alt.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(1).getPokemonID() +".jpg"));
            idSecim1 = insan.kartListesi.get(1).getPokemonID();
            secim1 = 2;


            pcSecilen = pc1.kartListesi.get(n);
            Ust.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(n).getPokemonID() +".jpg"));
            idSecim2 = pc1.kartListesi.get(n).getPokemonID();
            secim2 = n+1;

            tiklanan = "Alt2";
            tiklanan2 = "Ust"+secim2;
            System.out.println(tiklanan2);
            Alt2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            
            if("Ust1".equals(tiklanan2)){
                Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust1.setEnabled(false);
            }
            if("Ust2".equals(tiklanan2)){
                Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust2.setEnabled(false);
            }
            if("Ust3".equals(tiklanan2)){
                Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust3.setEnabled(false);
            }
      
        }
        else{
        
        Random rand = new Random();
        int n = rand.nextInt(pc1.kartListesi.size());
        
        insanSecilen = insan.kartListesi.get(1);
        Alt.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(1).getPokemonID() +".jpg"));
        idSecim1 = insan.kartListesi.get(1).getPokemonID();
        insan.kartListesi.remove(1);
        secim1 = 2;
        
        
        pcSecilen = pc1.kartListesi.get(n);
        Ust.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(n).getPokemonID() +".jpg"));
        idSecim2 = pc1.kartListesi.get(n).getPokemonID();
        pc1.kartListesi.remove(n);
        secim2 = n+1;
        
        tiklanan = "Alt2";
        tiklanan2 = "Ust"+secim2;
        System.out.println(tiklanan2);
        if(sayac3==0)
            Alt2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
        }
    }//GEN-LAST:event_Alt2ActionPerformed

    private void SavasButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavasButonActionPerformed
        
        
        
        if(kontrolListesi.get(idSecim1-1) > kontrolListesi.get(idSecim2-1)){
            WinorLose.setText("İnsan Kazandı!");
            System.out.println(kontrolListesi.get(idSecim1-1) + "\n" + kontrolListesi.get(idSecim2-1));
            sayac1 += 1;
        }
        else if(kontrolListesi.get(idSecim1-1) == kontrolListesi.get(idSecim2-1)){
            WinorLose.setText("Berabere!");
        }
        else{
            WinorLose.setText("Pc Kazandı!");
            System.out.println(kontrolListesi.get(idSecim1-1) + "\n" + kontrolListesi.get(idSecim2-1));
            sayac2 += 1;
        }
        
        insanSkor.setText(String.valueOf(sayac1));
        pcSkor.setText(String.valueOf(sayac2));
        
        if(anaSecim==1){
            dagit.doClick();
            
        Random rand = new Random();
        int n = getRandomWithExclusion(rand, 0, 2, blokList2);
        
        switch (n) {
        case 0 :
            Alt1.doClick();
            break;

        case 1 :
            Alt2.doClick();
            break;

        case 2 :
            Alt3.doClick();
            break;
        }
        }
        System.out.println(sayac1);
        System.out.println(sayac2);
    }//GEN-LAST:event_SavasButonActionPerformed

    private void Alt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alt3ActionPerformed
        
        if(sayac3<=0){
            Alt3.setEnabled(false);
            Random rand = new Random();
            int n = getRandomWithExclusion(rand, 0, 2, blokList);
            blokList.add(n);
            blokList2.add(2);
            
            insanSecilen = insan.kartListesi.get(2);
            Alt.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(2).getPokemonID() +".jpg"));
            idSecim1 = insan.kartListesi.get(2).getPokemonID();
            //insan.kartListesi.remove(2);
            secim1 = 3;


            pcSecilen = pc1.kartListesi.get(n);
            Ust.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(n).getPokemonID() +".jpg"));
            idSecim2 = pc1.kartListesi.get(n).getPokemonID();
            //pc1.kartListesi.remove(n);
            secim2 = n+1;

            tiklanan = "Alt3";
            tiklanan2 = "Ust"+secim2;
            
            Alt3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
            
            if("Ust1".equals(tiklanan2)){
                Ust1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust1.setEnabled(false);
            }
            if("Ust2".equals(tiklanan2)){
                Ust2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust2.setEnabled(false);
            }
            if("Ust3".equals(tiklanan2)){
                Ust3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\arka.png"));
                Ust3.setEnabled(false);
            }
        }
        else{
        
        Random rand = new Random();
        int n = rand.nextInt(pc1.kartListesi.size());
        
        insanSecilen = insan.kartListesi.get(2);
        Alt.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ insan.kartListesi.get(2).getPokemonID() +".jpg"));
        idSecim1 = insan.kartListesi.get(2).getPokemonID();
        insan.kartListesi.remove(2);
        secim1 = 3;
        
        
        pcSecilen = pc1.kartListesi.get(n);
        Ust.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "\\src\\main\\java\\Pokemon\\"+ pc1.kartListesi.get(n).getPokemonID() +".jpg"));
        idSecim2 = pc1.kartListesi.get(n).getPokemonID();
        pc1.kartListesi.remove(n);
        secim2 = n+1;
        
        tiklanan = "Alt3";
        tiklanan2 = "Ust"+secim2;
        System.out.println(tiklanan2);
        
        }
    }//GEN-LAST:event_Alt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alt;
    private javax.swing.JButton Alt1;
    private javax.swing.JButton Alt2;
    private javax.swing.JButton Alt3;
    private javax.swing.JPanel Anasayfa;
    private javax.swing.JButton SavasButon;
    private javax.swing.JPanel SavasSayfasi;
    private javax.swing.JButton Ust;
    private javax.swing.JButton Ust1;
    private javax.swing.JButton Ust2;
    private javax.swing.JButton Ust3;
    private javax.swing.JLabel WinorLose;
    private javax.swing.JButton dagit;
    private javax.swing.JLabel insanSkor;
    private javax.swing.JButton insanvspc_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pcSkor;
    private javax.swing.JButton pcvspc_Button;
    // End of variables declaration//GEN-END:variables
}
